### ISSUE TITLE
Rename Title and add image to tab

### ISSUE THREAD

**Issue by himanshu1221** [YadnikaDabhade/Restaurant-FoodWeb#5]
ill add a new title to tab and will add an  main logo to it it will look like this 
![Screenshot from 2022-12-08 12-32-01](https://user-images.githubusercontent.com/32031706/206380566-30f9316f-905d-4354-8e05-68bb14f9c4ed.png)

**Comment by SomilRathore01** [comment]
Hey @YadnikaDabhade can you please assign this project to me for competing in KWOC 2022
