### ISSUE TITLE
Adding footer

### ISSUE THREAD

**Issue by sakshipratap** [YadnikaDabhade/Restaurant-FoodWeb#7]
I would like to add footer to FoodWeb page for authorship and copyright information.

**Comment by DHRUVKHANDELWAL00** [comment]
hey @sakshipratap , can u assign me this. also can u  elaborate more on what u need on this issue

**Comment by YadnikaDabhade** [comment]
> I would like to add footer to FoodWeb page for authorship and copyright information.

@sakshipratap sure, you can work on it

**Comment by Muditb-21** [comment]
Hi !
 I want to work on this issue. Can you please assign it to me under kwoc2022?

**Comment by YadnikaDabhade** [comment]
> Hi ! I want to work on this issue. Can you please assign it to me under kwoc2022?

@Muditb-21 it is already assigned

**Comment by YadnikaDabhade** [comment]
> I would like to add footer to FoodWeb page for authorship and copyright information.

@sakshipratap you are running late , already someone has created the footer so now you have to use your creativeness to make it more attractive..and if you not willing to work on it so you can work on any another section.

**Comment by sakshipratap** [comment]
> > I would like to add footer to FoodWeb page for authorship and copyright information.
> 
> @sakshipratap you are running late , already someone has created the footer so now you have to use your creativeness to make it more attractive..and if you not willing to work on it so you can work on any another section.

Yes, I tried to update the existing footer. Kindly check it once, I've created a pull request.
